# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dec09aaac15d2f8e7cb1bd3ffd90efae17822d750bbd98159cfb8908513eeebf0fb92f2cb35444bc9ad67226b2ad5b17d30b0d81b97fb0459d45f93c43b5836

test:
  secret_key_base: 8bd8ea84628682fa4772d502ad929b0ed2ee990acbcdf8aaddeb24cd9572728064fefeb0cf5010017f7cc0531bfb115d8623e322dacaf0156fb43dcded9a804d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
